### ISSUE TITLE
API persistence

### ISSUE THREAD

**Issue by 7flash** [exhibitionist-digital/ultra#108]
It seems this example relies on API persistence, but it's not supported yet

https://github.com/exhibitionist-digital/ultra-examples/blob/d1a2be6441d78e0769f5c9138bf087973b22d5f0/src/api/github.js#L3

**Comment by 7flash** [comment]
...to continue https://github.com/exhibitionist-digital/ultra/issues/95

**Comment by 7flash** [comment]
It seems like LRU will be initialized again each time... meaning it will never have cache saved..

**Comment by mashaal** [comment]
I believe this is an issue only `dev`, where the API routes get re-initialised on each request. We have just merged a new updated dev server where this doesn't seem to be happening. It should be released with v1.1.0.

But, we are looking at re-implementing our API routes in the near future, so this might change a little bit soon.

![api-persist](https://user-images.githubusercontent.com/6100364/165510332-95d8ea15-dfb3-48d9-bcc1-af2985269534.gif)

**Comment by deckchairlabs** [comment]
This wouldn't work in production either, unless you can guarantee that the server instance will always be running, and never restart (probably unlikely).

**Comment by deckchairlabs** [comment]
What are you trying to achieve with persistence?

**Comment by deckchairlabs** [comment]
Keep in mind, Deno has APIs for this kind of thing, depending on where and how you deploy. But that would be getting off topic https://deno.land/manual/runtime/web_storage_api

**Comment by mashaal** [comment]
> Keep in mind, Deno has APIs for this kind of thing, depending on where and how you deploy. But that would be getting off topic https://deno.land/manual/runtime/web_storage_api

I've updated our example website to use these instead... it's a better fit for the purposes of a non-critical cache.

Really cool that this stuff works in Deno.

https://github.com/exhibitionist-digital/ultra-examples/blob/3445418d1764cfdcee6bbb7d341392a9026cb2d9/src/api/docs.js#L10
