### ISSUE TITLE
How to add TypeScript to react project?

### ISSUE THREAD

**Issue by marcustut** [exhibitionist-digital/ultra#11]
Hi, I was looking at the project and it was definitely a great work! 

I was running few of the examples provided and all of them are written in JavaScript, how do I add typescript support to them? Also, since there is no build system such as webpack and stuff, will libraries like TailwindCSS works?

**Comment by mashaal** [comment]
Thanks @marcustut. You should be able to change the file extensions to `.tsx` and start writing TypeScript. 

Keep in mind that file extensions are important here, and you will need to ensure you are including `.jsx` or `.tsx` in your imports (both top level and dynamic) throughout your components.

We have a few more examples in the works, and some of those will be using TS as a base.

That is correct, there is no build step atm, but this is a very loose definition as we are using esbuild to transpile jsx/tsx, so it may be possible to have an entry into CSS-in-JS or CSS modules in the future.

I am quite excited to try these out: https://css-tricks.com/css-modules-the-native-ones
