### ISSUE TITLE
Update contributor guidelines

### ISSUE THREAD

**Issue by cdoremus** [exhibitionist-digital/ultra#118]
As Ultra approaches the release of version 2, it seems like we need update our [contributor guidelines](/exhibitionist-digital/ultra/blob/master/CONTRIBUTING.md) to assure that code quality is maintained. We might want to start with the [Deno style guide](https://deno.land/manual/contributing/style_guide.md) and add/subtract our own wrinkles  

Please note the items you want to add or change in our contributor guidlines below.

**Comment by cdoremus** [comment]
My particular pet peeve at this point is to make sure that all functions and class methods have typed arguments and return values. Besides helping someone reviewing the code, it also is a big aid in developing and updating unit tests.

**Comment by deckchairlabs** [comment]
Linting should surely be picking all this up. Not sure about the return types though, as they're probably inferred by default. Maybe something we need to configure in the lint settings

**Comment by deckchairlabs** [comment]
linter PR #119

**Comment by deckchairlabs** [comment]
I personally think we should follow all the above. Would like to know how others feel about it @mashaal @dburles

**Comment by cdoremus** [comment]
Fixed in PR #122
