### ISSUE TITLE
Disable Hydration/Partial Hydration

### ISSUE THREAD

**Issue by lordanubi** [exhibitionist-digital/ultra#125]
HI is there any way to do this? I didn't see anything on the docs. It's pretty useful when you have a lot of statics nodes which don't need reactivity and they would slow the app performance without reason. I think people usually don't need Hydration on the whole tree

**Comment by mashaal** [comment]
This has been on our radar, but not a high priority at the moment. I agree, this would be nice.

@deckchairlabs, we're you working on this concept?

**Comment by mashaal** [comment]
This is outside of the scope of Ultra atm
