### ISSUE TITLE
Support for Material UI

### ISSUE THREAD

**Issue by notangelmario** [exhibitionist-digital/ultra#133]
Material UI seems to not be fully supported. Importing @mui/material does some weird stuff to rendering and hot reloading seems to break the components.

**Comment by mashaal** [comment]
V2 now makes it easier to customise your server and client rendering.

https://github.com/exhibitionist-digital/ultra/tree/main/examples

It may be possible to create a custom integration by following this:

https://mui.com/material-ui/guides/server-rendering/#the-server-side
