### ISSUE TITLE
Remove deno.json dependency

### ISSUE THREAD

**Issue by dionjwa** [exhibitionist-digital/ultra#135]
Firstly thanks for a really great project and documentation. It's exciting. 

The `deno.json` file is used mainly as a task launcher.

However I use [just](https://github.com/casey/just/blob/master/justfile) for all my task/commands.

Since the `importMap` is specified manually in one of the tasks in `deno.json`, this could be applied to all the tasks, rendering the `deno.json` mostly optional.

I would rather use a different task/command launcher like `just` and remove `deno.json`, but if I do this, `ultra` fails at 

```
https://deno.land/x/ultra@v1.0.1/src/config.ts:10:6
```

**Comment by mashaal** [comment]
We opted for the `deno.json` file as this is a dependency free runner/config in deno. Our V2 is a massive overhaul of how our server runs, and this might no longer be an issue as you can specify the importMap location via the `createServer` method.

https://github.com/exhibitionist-digital/ultra/blob/main/examples/basic/server.tsx#L6
