### ISSUE TITLE
Access request URL (for search params)

### ISSUE THREAD

**Issue by dionjwa** [exhibitionist-digital/ultra#136]
It's not clear how, or if it's possible, to access the request URL for the purposes of inspecting the pathname and search params and rendering based on that information.

Is it possible? Are there examples? The use of `wouter` to accomplish this isn't clear.

**Comment by mashaal** [comment]
Very interesting find, I wasn't aware of this limitation.

It seems this is being tracked in wouter here: https://github.com/molefrog/wouter/issues/58

I'm not sure if atm this can be solved with wouter, but it's worth noting that our V2 release allows you to BYO routing lib.

**Comment by deckchairlabs** [comment]
In v2 this is possible, I've updated our wouter example to include how this could be done. Although, would be far better if wouter had this support baked in.

https://github.com/exhibitionist-digital/ultra/tree/main/examples/with-wouter

The secret sauce is a custom context provider, and some event listening.
