### ISSUE TITLE
proposal: ultra.config.js feedback wanted

### ISSUE THREAD

**Issue by deckchairlabs** [exhibitionist-digital/ultra#149]
I'd like to reduce some duplication of configuration passed to both `createServer` and `createBuilder` 

So something like this. Thoughts?

```js
export default {
  browserEntrypoint: './client.tsx',
  serverEntrypoint: './server.tsx',
}
```

**Comment by mashaal** [comment]
Would simplify both server and builder, but I wonder if it's too soon to add something like this? Maybe we see how it goes using them in the wild without this first?

**Comment by deckchairlabs** [comment]
I suppose we don't need to build support into ultra itself, since you could just create a config file and import that
