### ISSUE TITLE
twind not working with suspense

### ISSUE THREAD

**Issue by epotter2297** [exhibitionist-digital/ultra#153]
When I put something inside of `<Suspense>` that has twind styles, it will fail to correctly display the styles on the first load of the route. On the second load, it will work correctly.

[Here](https://github.com/epotter2297/ultra-sample) is a repo I made to showcase the issue

![GIF of problem](https://media.giphy.com/media/cEfVQpRR3YSzwMhmPC/giphy.gif)

**Comment by mashaal** [comment]
I think there was an error in how these integrations were scaffolded out in your example.

Here is a fork of your repo that seems to be working as intended.

https://github.com/mashaal/ultra-sample/commit/6e678406c9c4f332350ad96711f571832a885962

I followed the examples found here https://github.com/exhibitionist-digital/ultra/tree/main/examples to debug this, though this could be a bit more elegant.

**Comment by mashaal** [comment]
![Kapture 2022-09-02 at 08 37 44](https://user-images.githubusercontent.com/6100364/188024511-39755f98-79dd-49ea-93b8-81cd4c41a624.gif)
