### ISSUE TITLE
wrong entry into built importMap.server.json

### ISSUE THREAD

**Issue by dagda1** [exhibitionist-digital/ultra#156]
After running `deno task build` there should be an entry for the root  file entry point `server.tsx` but instead of it having the `.tsx` extension it is `.js`:

```json
{
  "imports": {
    "./server.js": "./server.js",
```

Manually changing it to this fixes it:

```json
{
  "imports": {
    "./server.tsx": "./server.js",
```

**Comment by deckchairlabs** [comment]
This will be fixed in the next beta release! Apologies for the delay

**Comment by deckchairlabs** [comment]
This is fixed in the latest beta release
