### ISSUE TITLE
Allowing local SSL certificates + optimising stream chunking

### ISSUE THREAD

**Issue by barthuijgen** [exhibitionist-digital/ultra#17]
Running it locally does not stream anything because it will use http1.1 without tls, I had to change the code to allow passthrough of certificates to oak to enable http2 locally.

I understand it's mostly an experimental project at this stage, but it would be nice to think ahead a bit and make sure it is flexible enough in usage of oak. Might want to consider even moving it more to a plugin/middleware architecture instead of completely abstracting oak?

**Comment by mashaal** [comment]
Thanks @barthuijgen -- I see that with oak, the key and cert need to be passed into the `listen` call. I will allow this to be configured in the next update.

The current version allows configuration of both the oak `app` and `router` instance. 

```js
import ultra, { app } from "https://deno.land/x/ultra@v0.6/mod.ts";

// logger middleware
app.use(async (context, next) => {
  await next();
  const rt = context.response.headers.get("X-Response-Time");
  console.log(`${context.request.method} ${context.request.url} - ${rt}`);
});

await ultra({
  importmap: await Deno.readTextFile("importmap.json"),
});
```

**Comment by barthuijgen** [comment]
After going through it myself I found out it happened because the configured `chunkSize` was never being met. After a lot of fixes (including supporting .ts files) and modyfing `pushBody` to flush it's buffer after 10ms of no new chunks, it now works much better and loads in things just like the example.

For reference:

```
async function pushBody(reader, controller, chunkSize) {
  const startStream = Date.now();
  let parts = [] as any[];
  let partsSize = 0;

  let idleTimeout = 0;
  const idleFlush = () => {
    const write = concat(...parts);
    parts = [];
    partsSize = 0;
    controller.enqueue(write);
  };

  while (true) {
    const read = await reader.read();
    console.log(`chunk at ${Date.now() - startStream} size ${partsSize}`);
    if (read.done) break;
    partsSize += read.value.length;
    parts.push(read.value);
    if (partsSize >= chunkSize) {
      const write = concat(...parts);
      parts = [];
      partsSize = 0;
      if (write.length > chunkSize) {
        parts.push(write.slice(chunkSize));
      }
      controller.enqueue(write.slice(0, chunkSize));
    } else {
      if (idleTimeout) clearTimeout(idleTimeout);
      idleTimeout = setTimeout(idleFlush, 10);
    }
  }
  if (idleTimeout) clearTimeout(idleTimeout);
  controller.enqueue(concat(...parts));
}
```

**Comment by barthuijgen** [comment]
Sure, I'll do that. Wasn't sure if I should because my changes are very experimental. Delaying arbitrarily for 10ms didn't seem ideal either.

Any idea what would be the ideal way to flush tiny chunks from the render stream?

I was mainly trying to find out why the master branch for me locally was not behaving the same as your online demo.

**Comment by barthuijgen** [comment]
I see, i did notice printing all chunks that react outputs a ton of tiny parts so grouping does make sense, just need to make sure to send to the browser as soon as it's relevant and sometimes that's very little in terms of length.

like for testing i added a couple more components with delays of 1,2 & 3 seconds. They can all show directly but are very tiny html.

Anyway, PR is open, we can try to find the best approach

**Comment by mashaal** [comment]
This original issue of streaming locally does seem to be resolved now.
