### ISSUE TITLE
Update create script to include usage of `useAsset`

### ISSUE THREAD

**Issue by mashaal** [exhibitionist-digital/ultra#171]
The create script doesn't include `useAsset` for the CSS file, which breaks the prod builds -- we should double check the other examples as well in case we missed them as well.

**Comment by B3nten** [comment]
It should probably be clearer in the docs that useAsset is required for loading assets...

**Comment by deckchairlabs** [comment]
> It should probably be clearer in the docs that useAsset is required for loading assets...I had no idea.

By default it's required, since build will append the content hash of files to the filename eg. `style.css -> style.[hash].css`

**Comment by mashaal** [comment]
> It should probably be clearer in the docs that useAsset is required for loading assets...I had no idea.

Yea, I agree that this should be clearer -- also need to doc how to use assets with CSS
