### ISSUE TITLE
Problem on the Ultra web site front page???

### ISSUE THREAD

**Issue by cdoremus** [exhibitionist-digital/ultra#175]
Is this a feature or a bug (:smile:)  on the Ultra web site (font page)?

![Screenshot from 2022-09-27 12-55-33](https://user-images.githubusercontent.com/942174/192589314-32741324-f68a-4662-8ac5-b5ea6acd94b0.png)

It looks like MDX variable interpolation is not working properly.

**Comment by mashaal** [comment]
Haha, that is legit how it's supposed to look, I thought maybe the italic purple might be a strong enough stylistic choice to get this one over.

**Comment by deckchairlabs** [comment]
Lol, add a hover effect that reveals the current year?

**Comment by cdoremus** [comment]
FWIW  it looks a bit amateur to me. Why not use
```new Date().getFullYear()``` instead?
