### ISSUE TITLE
Fails to load dynamic routes when opened directly (opening from the address bar, not redirecting to it via code)

### ISSUE THREAD

**Issue by roj1512** [exhibitionist-digital/ultra#213]

**Comment by roj1512** [comment]
This is most probably related to the import maps.

**Comment by roj1512** [comment]
TL;DR

A dynamic route is at `/foo/bar`, and the import map entries like `./vendor/...` and `./src/...` lead to `/foo/vendor/...` and `/foo/src/...` which will then be 404, hence return `text/html`, and not the wanted script.

I could only reproduce this in production build.

**Comment by deckchairlabs** [comment]
This is fixed in v2.1.3

**Comment by roj1512** [comment]
@deckchairlabs Seems like the location is now fixed, but it is trying to load `.tsx` instead of the production `.js`. Should we reopen this? :)

**Comment by roj1512** [comment]
Browser

![image](https://user-images.githubusercontent.com/49933115/203301143-1780824e-6358-4592-850e-dbb24e7840b1.png)

**Comment by roj1512** [comment]
The error

```text
Uncaught (in promise) Error: Unsupported Content-Type "text/html; charset=utf-8" loading https://host:port/src/app.tsx imported from https://host:port/client.b3e5c79f.js. Modules must be served with a valid MIME type like application/javascript.
```

**Comment by roj1512** [comment]
![image](https://user-images.githubusercontent.com/49933115/203301697-81335b95-5728-456d-8ed6-967b10e2231e.png)

**Comment by roj1512** [comment]
Yes, that `<base href="/" />` fixes it.
