### ISSUE TITLE
The `ignored` option is not working

### ISSUE THREAD

**Issue by roj1512** [exhibitionist-digital/ultra#221]
No file or directory can be ignored when building.

**Comment by deckchairlabs** [comment]
Hey @roj1512  thanks for reporting, could you please add a reproduction of your build config?

**Comment by deckchairlabs** [comment]
In the new release `2.1.5` if your ignore pattern ends with a `/` it now assumes that you want to deeply ignore anything matching that pattern!

So doing the below (for instance) would now work

```ts
builder.ignore('./.git/')
```

**Comment by roj1512** [comment]
Thanks, and sorry for not being so active.

**Comment by roj1512** [comment]
I’ve just upgraded to 2.1.5.

- The `.git` directory is now ignored, but it still copies some unwanted files.

Here’s my config:

![image](https://user-images.githubusercontent.com/49933115/205621050-19fe04aa-0a59-4519-b8c5-28e20c9972e1.png)

And here is the unexpected result:

![image](https://user-images.githubusercontent.com/49933115/205621218-8aef8cc3-2e8d-41c0-a12a-9ce36c274d69.png)

**Comment by deckchairlabs** [comment]
It needs to end with a slash unfortunately, just because of how https://deno.land/std@0.167.0/path/glob.ts?s=globToRegExp works

**Comment by roj1512** [comment]
@deckchairlabs What about https://github.com/exhibitionist-digital/ultra/issues/221#issuecomment-1337137357

**Comment by roj1512** [comment]
@deckchairlabs are you still with me here?

**Comment by roj1512** [comment]
I want to ignore single files

https://github.com/exhibitionist-digital/ultra/issues/221#issuecomment-1337137357

**Comment by deckchairlabs** [comment]
Hi @roj1512 yes still here! Just haven't had the time to look into a solution for this. Could you open a separate issue for ignoring single files? Thanks!

**Comment by roj1512** [comment]
That’s pretty fine, take your time! Sure, I’m doing it right now.

**Comment by deckchairlabs** [comment]
In the meantime it looks like if you make the "patterns" relative it works okay in my testing eg.

```ts
ignored: [
  "./.gitignore"
]
```
