### ISSUE TITLE
WASM dependencies are not cached

### ISSUE THREAD

**Issue by roj1512** [exhibitionist-digital/ultra#222]
The WASM dependencies that are required to build projects are not cached, hence redownloaded every time a build is made.

**Comment by roj1512** [comment]
This and #221 increase the time needed to build and deploy a lot.

**Comment by deckchairlabs** [comment]
Hey @roj1512 thanks for reporting, are these dependencies of your project?

I've found WASM isn't cached correctly with Deno (probably a bug to be fixed on their end to be honest, although haven't dived into it too much)

What I've ended up doing, in Ultra in particular is using https://github.com/denosaurs/cache to cache the WASM dependency. An example from Ultra below.

```ts
import init, {
  transform,
} from "https://esm.sh/@swc/wasm-web@1.3.11/wasm-web.js";
import { cache } from "https://deno.land/x/cache@0.2.13/mod.ts";
import { toFileUrl } from "https://deno.land/std/path/mod.ts";

const fileToCache = await cache(
  "https://esm.sh/@swc/wasm-web@1.3.11/wasm-web_bg.wasm",
);

await init(toFileUrl(fileToCache.path));
```

**Comment by roj1512** [comment]
No, Ultra's dependencies.

**Comment by roj1512** [comment]
First build

![image](https://user-images.githubusercontent.com/49933115/205622574-ae58a333-4ce7-477c-a2c3-5ecd28456391.png)

Second build with connection removed but `.ultra/` persisted

![image](https://user-images.githubusercontent.com/49933115/205622440-7c640899-c8d4-41e1-816e-ddcb4ebce8aa.png)

**Comment by deckchairlabs** [comment]
Ah I see! We probably need to open an issue on deno_graph, as they don't allow you to initialize the module with a custom WASM path, which we need to be able to cache that WASM dep.

**Comment by deckchairlabs** [comment]
I've opened a PR which will allow us to do this! https://github.com/denoland/deno_graph/pull/199
