### ISSUE TITLE
A way to customize the default "src"

### ISSUE THREAD

**Issue by nnmrts** [exhibitionist-digital/ultra#23]
So firstly, as a sidenote, I think the default cwd (where ultra looks for the app.jsx/app.tsx file) shouldn't even be "src" because the whole philosophy around ultra is that there is no "source", no "build", no transpiling stuf. It should just be called "website" or "root" or "public" in my opinion, or even better, it should just be the current directory the server file is in.

Secondly, and more important, I suggest that this should be customizable. I know, ultra seems to be one of those "zero-config" projects, and I really love that it is, but I believe that the cwd is such a fundamental part that there should just be a simple "cwd" or "root" setting when calling `ultra`, like so:

```js
import ultra from "https://deno.land/x/ultra@v0.6/mod.ts";

await ultra({
	importmap: await Deno.readTextFile("importmap.json"),
	cwd: "./"
});
```

If you (as in you, the maintainers of ultra) agree, I'll gladly add a pull request for this. I assume it wouldn't be **that** difficult to introduce this setting, but let's see.

**Comment by nnmrts** [comment]
After opening this issue I discovered https://github.com/exhibitionist-digital/ultra/pull/7, and I find the reasoning in there strange, because what is more common is not necessarily better. Even "source" instead of "src" would be better in my opinion, but whatever. As I said, this shouldn't really be the point of the issue, as there should just be away to customize the app folder name.

**Comment by mashaal** [comment]
@nnmrts Thanks, we did go back and forth between what a default directory should be, but I agree that making it customisable would be nice. I think due to needing a bit of config for either the oak server, or vercel/deno deployments, the project code would be easier managed living in a specific directory for the time being.
