### ISSUE TITLE
Suggest: remove extra dev port(4507)

### ISSUE THREAD

**Issue by ahuigo** [exhibitionist-digital/ultra#235]
I think there is no need to listen extra dev port(4507). The reasons are as follows:
1. Port 4507 may be occupied by other process.
2. It's hard to run multile examples via `deno task dev`.
3. If we run `deno test example/*/server.test.ts`, it's to heavy to open/close a listen port 4507.

If possible, I would like to submit this PR

**Comment by cdoremus** [comment]
At one point I thought that there was an environmental variable that optionally set the development port which would allow the running of different Ultra instances on the same machine.

**Comment by ahuigo** [comment]
> At one point I thought that there was an environmental variable that optionally set the development port which would allow the running of different Ultra instances on the same machine.

Not a same thing.

There are two ports:
1. The app port, default 8000.
2. The ultra development port, default 4507(Only when `ULTRA_MODE=development`)

I don't think it's necessary to take up two ports for either development or unit testing.

Ultra can fully share one port with App(default 8000)
<img width="657" alt="image" src="https://user-images.githubusercontent.com/1781999/210717574-23b9bfdc-3898-4b31-b3d7-2de95e880c69.png">
