### ISSUE TITLE
After build wouter/react-router refresh pages 

### ISSUE THREAD

**Issue by skorotkiewicz** [exhibitionist-digital/ultra#251]
In dev mode everything works fine, but after build navigation (<Link>) through App refresh every page.
Also in dev mode works websocket for [GunDB.js](https://gun.eco/docs/) but after build WS don't connect to the server.

And after build I receive error:
```
Uncaught Error: Parse error https://stealthpad.deno.dev/vendor/browser/esm.sh/v119/node_process.js:29:1689

Uncaught (in promise) Error: Unsupported Content-Type "text/html; charset=utf-8" loading http://localhost:8000/vendor/browser/esm.sh/v119/readable-stream@3.6.2/es2022/lib/internal/streams/stream.js imported from http://localhost:8000/vendor/browser/esm.sh/v119/readable-stream@3.6.2/es2022/lib/_stream_readable.js. Modules must be served with a valid MIME type like application/javascript.
```
Here is my code: https://github.com/skorotkiewicz/StealthPad

**Comment by mashaal** [comment]
Your repo seems to use Aleph? Do you know if that node process is being called by the GunDB library?
