### ISSUE TITLE
No cache busting?

### ISSUE THREAD

**Issue by sjc5** [exhibitionist-digital/ultra#268]
Hi there, wonderful project!

I am noticing that all my client modules are cached as `public, max-age=31536000, immutable` and have no hash or anything associated with the file names. It requires a hard reload (with browser cache disabled) to get latest version of the client modules.

Am I likely doing something dumb to have caused this not to work as you'd expect? To be clear, I would expect these assets to include content hashes in their filenames, or similar, so it would download a fresh copy when the code changes.

If this is something that we need to do manually with this framework, any recommendations on approach?

Thanks very much!
Sam

**Comment by B3nten** [comment]
Are you noticing this in production with a build, or in dev?

**Comment by sjc5** [comment]
Hi @B3nten. I'm noticing it in a production environment (Deno Deploy).

**Comment by sjc5** [comment]
It looks like this was due to using a custom file structure.

Instead of:

```
- ROOT:
  - server.tsx (server entry)
  - client.tsx (client entry)
  - src/
    ...stuff
```

I was doing:

```
- ROOT:
  - server/
    - index.tsx (server entry)
      ...stuff
  - client
    - index.tsx (client entry)
      ...stuff
```

Upon switching back to the file structure instantiated by the CLI, the files are indeed getting hashes appended. It would be preferred if the build tool didn't make assumptions around file structure (or at least if they were more explicit), but I'll go ahead and close.

Thanks!

**Comment by deckchairlabs** [comment]
> It looks like this was due to using a custom file structure.
> 
> Instead of:
> 
> ```
> - ROOT:
>   - server.tsx (server entry)
>   - client.tsx (client entry)
>   - src/
>     ...stuff
> ```
> 
> I was doing:
> 
> ```
> - ROOT:
>   - server/
>     - index.tsx (server entry)
>       ...stuff
>   - client
>     - index.tsx (client entry)
>       ...stuff
> ```
> 
> Upon switching back to the file structure instantiated by the CLI, the files are indeed getting hashes appended. It would be preferred if the build tool didn't make assumptions around file structure (or at least if they were more explicit), but I'll go ahead and close.
> 
> Thanks!

Yes we default to hashing assets within `src` and `public` although those entry points should be included as hash targets, so probably worth opening a separate issue, as that is a bug!
