### ISSUE TITLE
Only react18 example works

### ISSUE THREAD

**Issue by TreetopFlyer** [exhibitionist-digital/ultra#33]
when run, all examples produce
`
error: Relative import path "helmet" not prefixed with / or ./ or ../ and not in import map from "https://deno.land/x/ultra@v0.6/src/render.ts" at https://deno.land/x/ultra@v0.6/src/render.ts:4:32
`

except for **/react18**.
'server.js' in that example comments out the HTTP import url for Ultra and imports the library from the filesystem
https://github.com/exhibitionist-digital/ultra/blame/df89a163b24c03f823bde9ab94143baa6dd7bc42/examples/react18/server.js#L1

**Comment by mashaal** [comment]
Oh, the react example is pointing to the newer, unpublished version of ultra. I've just updated the others to match. But this will fix when the next release is published.
