### ISSUE TITLE
web3 project  error

### ISSUE THREAD

**Issue by puentesdiaz** [exhibitionist-digital/ultra#34]
When run 
cd web3 && make dev

i get:

`error: Relative import path "helmet" not prefixed with / or ./ or ../ and not in import map from "https://deno.land/x/ultra@v0.6/src/render.ts"
    at https://deno.land/x/ultra@v0.6/src/render.ts:4:32
make: *** [makefile:2: dev] Error 1
`

**Comment by mashaal** [comment]
related to #33. This should be fixed for the time being
