### ISSUE TITLE
Ultra stuck in loop with React Context

### ISSUE THREAD

**Issue by TreetopFlyer** [exhibitionist-digital/ultra#35]
In the following example with a React "Context object" that's used in more than one file, Ultra gets stuck in some download/transpile loop (either `dev` or `start`) after the initial http request comes in.

```
--- filesystem: ---
src
  |-- app.jsx
  |-- component.jsx
  
--- app.jsx ---
import React from "react";
import Component from "./component";
export const CTX = React.createContext(`default value`);
export default () => <div><h1>app.jsx</h1><Component/></div>;

--- component.jsx --- 
import React from "react";
import { CTX } from "./app";
export default () =>
{
    const getCtx = React.useContext( CTX );
    return <div><h2>component.jsx</h2>{ getCtx }</div>;
}
```

(I'm probably making a stupid mistake/not understanding isomorphic react though...)

**Comment by Sheraff** [comment]
Is this specific to React (or React Context)? or is it the circular dependency causing this (app requires component, and component requires app)?

**Comment by TreetopFlyer** [comment]
@Sheraff I'm not really sure, although things seem to work fine in this traditional client-side React example with the same setup (https://codesandbox.io/s/agitated-margulis-2cc79)

In the Ultra example above here's what I get in the console:
```
$ mode=dev deno run --no-check -A --import-map=importmap.json --unstable server.js
Listening: http://localhost:3000
(go to localhost in browser)
Download http://localhost:3000/app.js?ts=1643732942955
Transpile: in 2470.7134000000005ms
Download http://localhost:3000/component
Download http://localhost:3000/app.js?ts=1643732945971
Transpile: in 83.86290000000008ms
Download http://localhost:3000/component
Download http://localhost:3000/app.js?ts=1643732946418
Transpile: in 31.054700000000594ms
Download http://localhost:3000/component
Download http://localhost:3000/app.js?ts=1643732946871
Transpile: in 2.3398999999990338ms
(keeps repeating and page never loads)
```

**Comment by TreetopFlyer** [comment]
@mashaal I noticed in the current master that running in **dev** mode still causes the loop.
Running in **production** works perfectly though. 
I *really* like Ultra keep up the good work!
