### ISSUE TITLE
How to use 0.7?

### ISSUE THREAD

**Issue by tmikaeld** [exhibitionist-digital/ultra#37]
This project is really neat, I'm trying to understand how it works.

You're rendering the JSX modules and adding them to the buffer and return it to the response as a stream - which is shown on the site - and when the new JSX module finishes, what happens?  It's replaced with the new stream?

How do I run the 0.7 version? It mentions a different repo for examples?

**Comment by mashaal** [comment]
Hey @tmikaeld, thanks for being so keen! `0.7.0` is almost ready, we are hoping to publish it this week.

The new examples are not public yet, but if you wanted to see how the new version works, you can checkout `0.7.0`, cd into `workspace`, and run `make`.

That will start up a local dev server, and you can see/edit the project files in `workspace`.

**Comment by tmikaeld** [comment]
Awesome! Thanks @mashaal for the quick reply, checking it out now 👍 

What license will this be published under, MIT?

**Comment by mashaal** [comment]
Yes, it will be MIT

**Comment by tmikaeld** [comment]
I noticed when playing around with SWR, that it doesn't actually render the HTML where it is in the markup, but it appends it to the bottom of the markup and then the script moves it into place after the stream is completed. Which means that it renders as a hidden DIV element, so rendering pages using this would break SEO?

**Comment by mashaal** [comment]
The react stream renderer appends the HTML markup as the stream is sent through (before the stream is fully complete), but yes, there are SEO impacts which can stem from this regardless.

Here is a good discussion on how head tags are currently working. We are using the 'Injecting Into the SSR Stream' method described here.

https://github.com/reactwg/react-18/discussions/106

We are currently sending the stream as soon as we can, but I am curious to see some of the options other libraries and frameworks take in the coming months. Theoretically it would be possible to wait for the stream to complete fully before sending any response, that way the fully page content would be properly resolved.

**Comment by mashaal** [comment]
The example in the `workspace` directory is very minimal, if you wanted to have a look at a more sizeable example, we have made and deployed our personal website with the new version.

https://exhibitionist.digital

https://github.com/exhibitionist-digital/exhibitionist (clone and run `make`)

This is using the new Deno Deploy GitHub action that was revealed earlier today

https://deno.com/blog/deploy-static-files

**Comment by tmikaeld** [comment]
The new site looks awesome, love your sense of art direction! 🥇

**Comment by tmikaeld** [comment]
I was hoping when I saw this that I had missed something, like, that the buffer could be cleared after the first cache had been rendered and replace with the actual HTML-in place, but once it's streamed to the browser it cannot be changed. Anyway, I learned a lot about streaming and how it works, especially the new awesome Web APIs. Thanks for sharing this project and letting me in on the ride :-)
