### ISSUE TITLE
`Content-Type` headers for text responses should specify `charset=utf-8`

### ISSUE THREAD

**Issue by jaydenseric** [exhibitionist-digital/ultra#40]
`Content-Type` headers for text responses, including HTML pages and static assets such as CSS and JS, should specify `charset=utf-8`. Example:

```diff
- content-type: text/html
+ content-type: text/html; charset=utf-8
```

Otherwise quite a few unicode characters such as typographic quotes (`“”`) will display mangled.

For the main HTML page responses this can be somewhat mitigated with `<meta charset="UTF-8" />`, but even then it's still good to specific the charset directly in the response headers.

**Comment by mashaal** [comment]
Thanks for picking that up, fixed here: https://github.com/exhibitionist-digital/ultra/commit/83789ca3cf626cc46c32467c40fd0119312d3482
