### ISSUE TITLE
Hot module reload

### ISSUE THREAD

**Issue by melkir** [exhibitionist-digital/ultra#49]
Hello 👋 

I was playing with [demo](https://github.com/exhibitionist-digital/ultra-examples/tree/ultra-website) and the first thing that I've noticed is that there's no HMR available. This could greatly improve the devexp 🙂

Besides, I wonder if it would be possible to have some features similar to what NextJS does.
- Disabling Javascript makes the site unusable
- Switching to offline mode returns a 404 when navigating between pages, even if they have already been visited
- In slow connection, the first rendering takes several seconds to display the main page

Anyway, thanks for this framework, can't wait to see the future evolutions!

**Comment by mashaal** [comment]
Thanks for pointing these out. v0.8.0 will have:

- Websocket watcher to reload on source change
- a `renderToString` method for the streaming server, which would solve the `disabled js` issue, but this would nullify some of the benefits of streaming React 18 provides.

I believe the offline issue is our lack of handling that case with SWR in our codebase, I will have a look.
