### ISSUE TITLE
Replace "preload" with "prefetch" on website

### ISSUE THREAD

**Issue by Sheraff** [exhibitionist-digital/ultra#72]
[ultrajs.dev](https://ultrajs.dev/) uses `<link rel="preload" as="fetch">` for API JSON data that is not required immediately. The correct attribute to use for something that "might be needed later" is `<link rel="prefetch" as="fetch">`. 

Currently, chrome will drop the "preloaded" resources (/api/docs & /api/examples) and re-fetch them on navigation. It also logs the following warning multiple times:
> The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

With "prefetch" chrome would save them in cache for a few minutes.

**Comment by mashaal** [comment]
Ah, good catch!
