### ISSUE TITLE
Improve server start time

### ISSUE THREAD

**Issue by mashaal** [exhibitionist-digital/ultra#87]
Until this is shipped, initial Ultra server start times will be slow. I wonder if there is a temp fix we can implement to improve this for now? Include SWC and deno_graph downloads to a temp dir local to project?

https://github.com/denoland/deno/issues/2552

@deckchairlabs

**Comment by deckchairlabs** [comment]
May have already committed a fix to master, I've got to make sure I'm working on my fork...

https://github.com/exhibitionist-digital/ultra/commit/20601b1368ecc875f21bb874031e778e6b793374

**Comment by deckchairlabs** [comment]
I think we should move deno_graph from deps, and maybe have separate dev_deps?

**Comment by mashaal** [comment]
> May have already committed a fix to master, I've got to make sure I'm working on my fork...
> 
> [20601b1](https://github.com/exhibitionist-digital/ultra/commit/20601b1368ecc875f21bb874031e778e6b793374)

It is orders of magnitude faster, would this effect client apps as well?

I'll make a `deps.dev.ts` PR
