### ISSUE TITLE
Tailwind, Windi, Twind, UnoCSS or similar Atomic CSS support

### ISSUE THREAD

**Issue by heinthanth** [exhibitionist-digital/ultra#89]
Hii,

This is feature request. Currently, I can import unocss/runtime script tag and generate CSS only the fly. But this is client side generation.

<img width="895" alt="Screen Shot 2022-04-24 at 8 55 42 PM" src="https://user-images.githubusercontent.com/43804263/164981243-c7ef65f5-efee-4bb1-b831-7551eb184193.png">

Can we have atomic CSS support with a nice SSR?

**Comment by mashaal** [comment]
Better CSS tooling has been on our list for a while. Ideally, we would love to have 1st class support for CSS module import assertions. Posting some links for reference...

https://github.com/denoland/deno/issues/11961
https://github.com/denoland/deno/issues/13898
https://daverupert.com/2021/08/css-modules-in-css-modules
https://github.com/guybedford/es-module-shims#css-modules

But these may still be a while off -- we can explore other options in the interim, unocss looks great.

**Comment by mashaal** [comment]
This one just came across my desk: https://open-props.style

This wouldn't require any changes to core to work, if anyone is interested

**Comment by cdoremus** [comment]
What about -- as a start -- to just minify the static CSS before it is deployed to prod. Use something like https://deno.land/x/minifier@v1.1.1

**Comment by deckchairlabs** [comment]
> What about -- as a start -- to just minify the static CSS before it is deployed to prod. Use something like https://github.com/postcss/postcss-deno with a minification utility.

Yeah this is a good idea, although I'd recommend using https://github.com/parcel-bundler/parcel-css

**Comment by heinthanth** [comment]
Yeah ... currently, only way is to write CSS separately, build it and import in Ultra.

**Comment by mashaal** [comment]
Twind, Emotion and Stitches should work in V2
