### ISSUE TITLE
variables in api are not mutable

### ISSUE THREAD

**Issue by 7flash** [exhibitionist-digital/ultra#95]
I have modified api/example.ts:

```
let value = 1;

export default () => {
  value++;
  const body = JSON.stringify({
    value,
  });
  return new Response(body, {
    headers: {
        'Content-Type': 'application/json',
    },
  });
};
```

I am expecting it each time to return increased value, but it always returns 1

**Comment by 7flash** [comment]
https://github.com/exhibitionist-digital/create-ultra-app/blob/main/src/api/example.ts

**Comment by TheNando** [comment]
Does the API support dynamic routes or at least query stings? Something alone the lines of a route like `pages/api/post/[pid].js` where you can access the post id within the handler.

**Comment by deckchairlabs** [comment]
I believe this is because the API route is imported/initialized on every request, so yes, you would be losing the mutability of the variables.

**Comment by mashaal** [comment]
Yes, that is correct, there is no persistence in the API routes atm -- I'm not sure there should be?

This is part of a bigger discussion on API routes moving forward in general. I'm going to close this, but read more here: 

👉 https://github.com/exhibitionist-digital/ultra/discussions/98
