### ISSUE TITLE
Are dynamic API routes supported?

### ISSUE THREAD

**Issue by TheNando** [exhibitionist-digital/ultra#96]
Does the API support dynamic routes or at least query stings? Something alone the lines of a route like pages/api/post/[pid].js where you can access the post id within the handler.

**Comment by TheNando** [comment]
I figured out how to get the query strings, but from looking through the code, there doesn't seem to be dynamic route support. I might take a stab at it and push up a PR.

```ts
export default (request) => {
  const headers = {
    "content-type": "application/json",
  };

  // The request contains the url which is just the string in the address bar, not a URL object
  const { url } = request

  const body = JSON.stringify({ test: "ok", url });

  return new Response(body, { headers });
};
```

**Comment by Industrial** [comment]
```ts
const url = new URL(request.url);
const params = new URLSearchParams(url.search);
```

**Comment by Industrial** [comment]
Supporting dynamic routes would be a different approach then the current routing system for SSR/frontend routes: https://ultrajs.dev/docs#routing

@mashaal maybe we can tie API routes into Wouter routes. That way you can decide how to parameterize them with Wouter and more importantly also have freedom in where to put them on disk.

**Comment by mashaal** [comment]
Yes, we've lightly discussed this in the Discord. We do need a way to allow dynamic API routing - I am not sure if this should be something like the fs routing in the original post, or if it should be set in a config when you start Ultra. I'm feeling like the latter is more inline with how the rest of Ultra works, and it might be a good start to adding some customisable middleware for other purposes?

**Comment by deckchairlabs** [comment]
You can use the Oak handler integration, which gives you a more powerful routing solution. https://github.com/exhibitionist-digital/ultra/blob/master/workspace/oak.ts

Current implementation of API routes I feel isn't inline with the rest of how Ultra works, it's based on filesystem (ala NextJS and others).

I'm of the opinion we drop our implementation of API routes, and recommend using a more advanced server handler.

**Comment by TheNando** [comment]
Just saw what you guys wrote. I took a stab at it anyways for fun and to better learn how the stack works. Take it or leave it.
https://github.com/exhibitionist-digital/ultra/pull/97

**Comment by dburles** [comment]
Maybe instead we could allow users to specify directories that shouldn't be served (so that dynamically imported api handlers can live there) in combination with an API route handler. Users can use URLPattern or whatever they like for route handling and dynamically import and execute the appropriate handler, eg:

```js
import ultra from "https://deno.land/x/ultra@v1.0.1/server.ts";

ultra({
  // optional
  apiHandler(request) {
     // handle api requests
  }
});
```

**Comment by dburles** [comment]
Actually perhaps all we need is middleware for the request handler.

```js
import ultra from "https://deno.land/x/ultra@v1.0.1/server.ts";

const server = ultra();

server.use((request, next) => { ... });
```

**Comment by dburles** [comment]
This would mean that @TheNando's filesystem based solution (and others) could be external modules and simply plugged in.

**Comment by deckchairlabs** [comment]
> This would mean that @TheNando's filesystem based solution (and others) could be external modules and simply plugged in.

Absolutely, I don't think we should be reinventing the wheel though. Plenty of more powerful server implementations out there that do everything someone would need.

I do agree we need some way of limiting what can be requested in the pathname eg. `/path/to/secret.js`

**Comment by deckchairlabs** [comment]
> Actually perhaps all we need is middleware for the request handler.
> 
> ```js
> import ultra from "https://deno.land/x/ultra@v1.0.1/server.ts";
> 
> const server = ultra();
> 
> server.use((request, response, next) => { ... });
> ```

Yeah I think this is the go, more generic, handles many use cases

**Comment by dburles** [comment]
> > This would mean that @TheNando's filesystem based solution (and others) could be external modules and simply plugged in.
> 
> Absolutely, I don't think we should be reinventing the wheel though. Plenty of more powerful server implementations out there that do everything someone would need.

At the moment `server.ts` uses [Deno's Simple HTTP server](https://deno.land/manual/examples/http_server) which doesn't have any concept of middleware, so we would have to write our own for our generic `requestHandler`. Which wouldn't be all that difficult.

> I do agree we need some way of limiting what can be requested in the pathname eg. `/path/to/secret.js`

This could be handled by middleware too.

**Comment by deckchairlabs** [comment]
We should move this to a new issue
